# Generated by Django 3.0.7 on 2020-06-27 08:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='id',
            new_name='uid',
        ),
        migrations.AlterField(
            model_name='humidityreading',
            name='reading',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='humidityreading',
            name='readingDateTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 27, 8, 19, 8, 882665, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tempraturereading',
            name='reading',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='tempraturereading',
            name='readingDateTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 27, 8, 19, 8, 881668, tzinfo=utc)),
        ),
    ]
